name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{vars.AZURE_WEBAPP_NAME}}   # set this to your application's name
  NODE_VERSION: '16.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install, build
        run: |
          npm install
      - name: create firebase json
        id: createFirebaseJson
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "env-key.json"
          json: ${{ secrets.FIREBASE_JSON }}
      - name: Zip artifact for deployment
        run: zip -r -q release.zip ./*
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: release.zip
          retention-days: 1
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip

#name: Deploying
#
#on:
#  push:
#    branches:
#      - dev
#jobs:
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: executing remote ssh commands using ssh key
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.AWS_HOST }}
#          username: ${{ secrets.AWS_USER }}
#          key: ${{ secrets.AWS_KEY }}
#          script: sh restart_dhaakad.sh

